routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/post/{id}',['as'=>'home.post','uses'=>'AdminPostsController@post']);
Route::get('/post/{id}','AdminPostsController@post')->name('post');;

// Llamo al middleware
Route::group(['middleware'=>'admin'], function() { 
    
    Route::get('/admin', function() {
        return view('layouts.admin1');
    });

    Route::resource('admin/users','AdminUserController');

    Route::resource('admin/posts','AdminPostsController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/comments','PostsCommentController');

    Route::delete('admin/delete/media','AdminMediaController@deleteMedia');

    Route::resource('admin/comments/replies','CommentRepliesController');

    // Route::get('admin/media/upload',['as'=>'admin.media.upoload','uses'=>'AdminMediaController@upload']);
    
});

// Route::resource('admin/users','AdminUserController');
Route::group(['middleware'=>'auth'], function() { 

    Route::post('comment/reply','CommentRepliesController@createReply');

});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
    protected $fillable = [
        'post_id',
        'author',
        'email',
        'photo',
        'body',
        'is_active'
    ];

    public function replies(){
        return $this->hasMany('App\CommentReply');
    }

    public function post(){
        return $this->belongsTo('App\Post');
    }
}

resources/views/admin/comments/index.blade.php
@extends('layouts.admin1')

@section('content')

    <h1>Comments</h1>

    @if(count($comments) > 0)

    <table class="table">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Author</th>
            <th scope="col">Email</th>
            <th scope="col">Body</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>

        @foreach($comments as $comment)
   
    
          <tr> 
            <td>{{ $comment->id}}</td>
            <td>{{ $comment->author}}</td>
            <td>{{ $comment->email}}</td>
            <td>{{ $comment->body}}</td>
            <td><a href="{{route('post', ['id' => 1]  )}}">View Post</a></td>
            {{--  ===========================  --}}
            {{--  Boton de aprobar/no aprobar  --}}
            {{--  ===========================  --}}
            <td>
              @if($comment->is_active === 1)
              
                    {!! Form::open(['method'=>'PATCH','action'=> ['PostsCommentController@update', $comment->id ] ]) !!}

                    <input type="hidden" name="is_active" value="0">
            
                    <div class="form-group">
                        {!! Form::submit('Un-approve', ['class'=>'btn btn-primary']) !!}
                    </div>
                    {!! Form::close() !!}
              @else

                  {!! Form::open(['method'=>'PATCH','action'=> ['PostsCommentController@update', $comment->id ] ]) !!}

                    <input type="hidden" name="is_active" value="1">
            
                    <div class="form-group">
                        {!! Form::submit('Approve', ['class'=>'btn btn-info']) !!}
                    </div>
                    
                    {!! Form::close() !!}

              @endif
            
            {{--  ===========================  --}}
            {{--  Boton de eliminar            --}}
            {{--  ===========================  --}}
            </td>
            <td>
                {!! Form::open(['method'=>'DELETE','action'=> ['PostsCommentController@destroy', $comment->id ] ]) !!}
        
                <div class="form-group">
                    {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
                </div>
                
                {!! Form::close() !!}
              </td>
          </tr>
        @endforeach
        </tbody>
      </table>

      @else

      <h1 class="text-content">No Comments </h1>

      @endif


@stop

resources/views/admin/comments/show.blade.php
{{--  En esta pagina puedo ver todos los comentarios del post (eliminados y no eliminados)  --}}

@extends('layouts.admin1')


@section('content')

    <h1>Posts</h1>

    
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<table class="table">
    <thead>
      <tr >
        <th scope="col">Id</th>
        <th scope="col">Photo</th>
        <th scope="col"> Owner </th>
        <th scope="col">Category</th>
        <th scope="col">Photo</th>
        <th scope="col">Title</th>
        <th scope="col">Body</th>
        <th scope="col">Updated</th>
      </tr>
    </thead>
    <tbody>
      @if($posts)

      @foreach($posts as $post)

      <tr> 
        <th>{{ $post->id}}</th>
        <td><img height="100" src="{{$post->photo ? $post->photo->file : 'http://placehold.it/400x400' }} " alt=""></td>
        <td><a href="{{route('posts.edit', $post->id )}}"> {{ $post->user->name}} </a></td>
        <td>{{ $post->category ? $post->category->name : 'Uncategorize'}} </td>
        <td>{{ $post->title}}</td>
        <td>{{ str_limit($post->body,30) }}</td>
        <td><a href="{{route('post', $post->id )}}"> </a> </td>
        <td><a href="{{route('comments.show', $post->id )}}"> </a> </td>
        <td>{{ $post->created_at}}</td>
        <td>{{ $post->updated_at}}</td>
      </tr>

      @endforeach

      @endif
    </tbody>
  </table>


@stop