routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/post/{id}',['as'=>'home.post','uses'=>'AdminPostsController@post']);
Route::get('/post/{id}','AdminPostsController@post')->name('post');;

// Llamo al middleware
Route::group(['middleware'=>'admin'], function() { 
    
    Route::get('/admin', function() {
        return view('layouts.admin1');
    });

    Route::resource('admin/users','AdminUserController');

    Route::resource('admin/posts','AdminPostsController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/comments','PostsCommentController');

    Route::delete('admin/delete/media','AdminMediaController@deleteMedia');

    Route::resource('admin/comments/replies','CommentRepliesController');

    // Route::get('admin/media/upload',['as'=>'admin.media.upoload','uses'=>'AdminMediaController@upload']);
    
});

// Route::resource('admin/users','AdminUserController');
Route::group(['middleware'=>'auth'], function() { 

    Route::post('comment/reply','CommentRepliesController@createReply');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use PhpParser\Node\Expr\FuncCall;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','photo_id','is_active','',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function setPasswordAttribute($password){
        if(!empty($password)){
            $this->attributes['password'] = bcrypt($password);
        }
    }

    // Checkea el rol
    public function isAdmin(){
        // if($this->role->name == "administrador" && $this->is_active == 1){
        if($this->role_id == 1 && $this->is_active == 1){
            return true;
        }
        return false;
    }

    public function posts(){
        return $this->hasMany('App\Post');
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin1')

@section('content')

    <h1>Create Users</h1>
    
    {!! Form::open(['method'=>'POST','action'=>'AdminUserController@store','files'=>true]) !!}

    <div class="form-group">
        
        {!! Form::label('name', 'Name') !!}
        {!! Form::text('name', null,['class'=>'form-control']) !!}
        
    </div>
    
    <div class="form-group">
        
        {!! Form::label('email', 'Email') !!}
        {!! Form::email('email', null,['class'=>'form-control']) !!}
        
    </div>

    <div class="form-group">
        
        {!! Form::label('role_id', 'Role') !!}
        {!! Form::select('role_id',[''=>'Chosse Options'] + $roles,['class'=>'form-control']) !!}
        
    </div>

    <div class="form-group">
        
        {!! Form::label('is_active', 'Status') !!}
        {!! Form::select('is_active', array(1=>'Active', 0=>'Not Active'), 0 ,['class'=>'form-control']) !!}
        
    </div>

    <div class="form-group">
        
        {!! Form::label('photo_id', 'Carga una imagen : ') !!} 
        {!! Form::file('photo_id', null ,['class'=>'form-control']) !!}
        
    </div>

    <div class="form-group">
        
        {!! Form::label('password', 'Password:') !!}
        {!! Form::password('password', array(1=>'Active', 0=>'Not Active'), 0 ,['class'=>'form-control']) !!}
        
    </div>
    {{--  BOTON PARA ENVIAR  --}}
    <div class="form-group">
        
        {!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
        
    </div>

    
    {!! Form::close() !!}

{{--  Cartel de errores  --}}
@include('includes.form_error')

@stop
    

resources/views/admin/users/edit.blade.php
@extends('layouts.admin1')

@section('content')

    <h1>Edit Users</h1>

    <div class="row">

        <div class="col-sm-3">
            <img height="200" src="{{$user->photo ? $user->photo->file :  'http://placehold.it/400x400' }}" alt="" class="img-responsive img-rounded">
        </div>

        <div class="col-sm-9">
        
            {!! Form::model($user,['method'=>'PATCH','route'=> ['users.update', $user ],'files'=>true]) !!}

            <div class="form-group">
                
                {!! Form::label('name', 'Name') !!}
                {!! Form::text('name', null,['class'=>'form-control']) !!}
                
            </div>
            
            <div class="form-group">
                
                {!! Form::label('email', 'Email') !!}
                {!! Form::email('email', null,['class'=>'form-control']) !!}
                
            </div>

            <div class="form-group">
                
                {!! Form::label('role_id', 'Role') !!}
                {!! Form::select('role_id',$roles,['class'=>'form-control']) !!}
                
            </div>

            <div class="form-group">
                
                {!! Form::label('is_active', 'Status') !!}
                {!! Form::select('is_active', array(1=>'Active', 0=>'Not Active'), null ,['class'=>'form-control']) !!}
                
            </div>
        
            <div class="form-group">
                
                {!! Form::label('photo_id', 'Carga una imagen : ') !!} 
                {!! Form::file('photo_id', null ,['class'=>'form-control']) !!}
                
            </div>

            <div class="form-group">
                
                {!! Form::label('password', 'Password:') !!}
                {!! Form::password('password', array(1=>'Active', 0=>'Not Active'), 0 ,['class'=>'form-control']) !!}
                
            </div>
            {{--  BOTON PARA GUARDAR  --}}
            <div class="form-group">
                
                {!! Form::submit('Update User', ['class'=>'btn btn-primary col-sm-6']) !!}
                
            </div>
                        
            {!! Form::close() !!}

            {{--  Formulario para eliminar  --}}
            {!! Form::open(['method'=>'DELETE','action'=> ['AdminUserController@destroy',$user->id ]]) !!}

            <div class="form-group">
                {!! Form::submit('Delete User', ['class'=>'btn btn-danger col-sm-6']) !!}
            </div>

            {!! Form::close() !!}

        </div>
    </div>
    <div class="row">
        {{--  Cartel de errores  --}}
        @include('includes.form_error')
    </div>

@stop
    

resources/views/admin/users/index.blade.php
@extends('layouts.admin1')


@section('content')

  @if(Session::has('delete_user'))
    <p class="bg-danger"> {{session('deleted_user')}} </p>
  @endif

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <h1>Users</h1>

    <table class="table">
        <thead>
          <tr >
            <th scope="col">Id</th>
            <th scope="col">Photo</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Role</th>
            <th scope="col">Status</th>
            <th scope="col">Created</th>
            <th scope="col">Updated</th>
          </tr>
        </thead>
        <tbody>
          @if($users)

          @foreach($users as $user)

          <tr> 
            <th>{{ $user->id}}</th>
            <td><img height="50" src="{{$user->photo ? $user->photo->file :  'http://placehold.it/400x400' }}" alt=""></td>
            <td><a href="{{route('users.edit', $user->id )}}"> {{ $user->name}} </a> </td>
            <td>{{ $user->email}}</td>
            <td>{{ $user->role->name}}</td>
            <td>{{ $user->is_active == 1 ? 'Active' : 'Not Active'}}</td>
            <td>{{ $user->created_at}}</td>
            <td>{{ $user->updated_at}}</td>
          </tr>

          @endforeach

          @endif
        </tbody>
      </table>
@stop