routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/post/{id}',['as'=>'home.post','uses'=>'AdminPostsController@post']);
Route::get('/post/{id}','AdminPostsController@post')->name('post');;

// Llamo al middleware
Route::group(['middleware'=>'admin'], function() { 
    
    Route::get('/admin', function() {
        return view('layouts.admin1');
    });

    Route::resource('admin/users','AdminUserController');

    Route::resource('admin/posts','AdminPostsController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/categories','AdminCategoriesController');

    Route::resource('admin/comments','PostsCommentController');

    Route::delete('admin/delete/media','AdminMediaController@deleteMedia');

    Route::resource('admin/comments/replies','CommentRepliesController');

    // Route::get('admin/media/upload',['as'=>'admin.media.upoload','uses'=>'AdminMediaController@upload']);
    
});

// Route::resource('admin/users','AdminUserController');
Route::group(['middleware'=>'auth'], function() { 

    Route::post('comment/reply','CommentRepliesController@createReply');

});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //
    protected $fillable= ['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin1')

@section('content')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <h1>Categories</h1>

    <div class="col-sm-6">
   
        {!! Form::model($category , ['method'=>'PATCH','action'=>['AdminCategoriesController@update', $category->id ]]) !!}

        <div class="form-group">
            
            {!! Form::label('name', 'Name : ') !!}
            {!! Form::text('name', null,['class'=>'form-control']) !!}
            
        </div>

        {{--  BOTON PARA actualizar  --}}
        <div class="form-group">
            
            {!! Form::submit('Update Category', ['class'=>'btn btn-primary']) !!}
            
        </div>

        {!! Form::close() !!}

    </div>
    <div class="col-sm-6">
    {{-- Eliminar  --}}
   
        {!! Form::model($category , ['method'=>'DELETE','action'=>['AdminCategoriesController@destroy', $category->id ]]) !!}

        {{--  BOTON PARA ELIMINAR  --}}
        <div class="form-group">
            
            {!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6']) !!}
            
        </div>

        {!! Form::close() !!}

    </div>

@stop

resources/views/admin/categories/index.blade.php
@extends('layouts.admin1')

@section('content')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <h1>Categories</h1>

    <div class="row">

        <div class="col-sm-6">
    
            {!! Form::open(['method'=>'POST','action'=>'AdminCategoriesController@store']) !!}

            <div class="form-group">
                
                {!! Form::label('name', 'Name : ') !!}
                {!! Form::text('name', null,['class'=>'form-control']) !!}
                
            </div>

            {{--  BOTON PARA ENVIAR  --}}
            <div class="form-group">
                
                {!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
                
            </div>

            
            {!! Form::close() !!}

        </div>

        <div class="col-sm-6">

        <table class="table">
            <thead>
                <tr >
                    <th scope="col">Id</th>
                    <th scope="col">Name</th>
                    <th scope="col">Created date</th>
                </tr>
                </thead>
            <tbody>
                @if($categories)

                @foreach($categories as $category)

                <tr> 
                    <th>{{ $category->id}}</th>
                    <td><a href="{{route('categories.edit',$category->id)}}"> {{ $category->name}}</td>
                    <td>{{ $category->created_at ? $category->created_at->diffForHumans() : 'no date'}}</td>
                </tr>

                @endforeach

                @endif
            </tbody>
            </table>
        </div>
    </div>
@stop